### ISSUE TITLE
_protector.Protect Not working after RC2 update

### ISSUE THREAD

**Issue by damienbod** [aspnet/DataProtection#146]
After updating to RC2, the data protection no longer works using PersistKeysToFileSystem

Startup:
```
var folderForKeyStore = Configuration["Production:KeyStoreFolderWhichIsBacked"];

var cert = new X509Certificate2(Path.Combine(_env.ContentRootPath, "damienbodserver.pfx"), "");

services.AddDataProtection()
	.SetApplicationName("AspNet5IdentityServerAngularImplicitFlow")
	.PersistKeysToFileSystem(new DirectoryInfo(folderForKeyStore))
	.ProtectKeysWithCertificate(cert);
```

Usage:
```
private void protectDescription(DataEventRecord dataEventRecord)
{
	var protectedData = _protector.Protect(dataEventRecord.Description);
	dataEventRecord.Description = protectedData;
}
```

Exception:
```	
{"Unable to retrieve the decryption key."

   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyEncryptorDelegate>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptorInstance()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.DataProtection.DataProtectionExtensions.Protect(IDataProtector protector, String plaintext)
   at AspNet5SQLite.Repositories.DataEventRecordRepository.protectDescription(DataEventRecord dataEventRecord) in C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\ResourceServer\Repositories\DataEventRecordRepository.cs:line 60
   at AspNet5SQLite.Repositories.DataEventRecordRepository.Post(DataEventRecord dataEventRecord) in C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\ResourceServer\Repositories\DataEventRecordRepository.cs:line 39
   at AspNet5SQLite.Controllers.DataEventRecordsController.Post(DataEventRecord value) in C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\ResourceServer\Controllers\DataEventRecordController.cs:line 38
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<>c__DisplayClass21_0.<WrapVoidActionAsync>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.ExecuteAsync(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionExecutor.ExecuteAsync(ObjectMethodExecutor actionMethodExecutor, Object instance, Object[] orderedActionArguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
 ```

Trace:
```
The thread 0x2fb0 has exited with code 0 (0x0).
The thread 0x2cb4 has exited with code 0 (0x0).
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 POST http://localhost:44390/api/DataEventRecords/ application/json 57
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: Successfully validated the token.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: HttpContext.User merged via AutomaticAuthentication from authenticationScheme: Bearer.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization was successful for user: 48421157.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization was successful for user: 48421157.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization was successful for user: 48421157.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Executing action method AspNet5SQLite.Controllers.DataEventRecordsController.Post (ResourceServer) with arguments (AspNet5SQLite.Model.DataEventRecord) - ModelState is Valid'
Exception thrown: 'System.Security.Cryptography.CryptographicException' in mscorlib.dll
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Error: An unhandled exception has occurred: Unable to retrieve the decryption key.

System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyEncryptorDelegate>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptorInstance()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.DataProtection.DataProtectionExtensions.Protect(IDataProtector protector, String plaintext)
   at AspNet5SQLite.Repositories.DataEventRecordRepository.protectDescription(DataEventRecord dataEventRecord) in C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\ResourceServer\Repositories\DataEventRecordRepository.cs:line 60
   at AspNet5SQLite.Repositories.DataEventRecordRepository.Post(DataEventRecord dataEventRecord) in C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\ResourceServer\Repositories\DataEventRecordRepository.cs:line 39
   at AspNet5SQLite.Controllers.DataEventRecordsController.Post(DataEventRecord value) in C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\ResourceServer\Controllers\DataEventRecordController.cs:line 38
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<>c__DisplayClass21_0.<WrapVoidActionAsync>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.ExecuteAsync(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionExecutor.ExecuteAsync(ObjectMethodExecutor actionMethodExecutor, Object instance, Object[] orderedActionArguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: Successfully validated the token.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: HttpContext.User merged via AutomaticAuthentication from authenticationScheme: Bearer.
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 2443.3954ms 404 
```

**Comment by damienbod** [comment]
@blowdart Cert was added to the cert store, personal certs and now it works 

Thanks
