### ISSUE TITLE
ProtectKeysWithDpapi results in System.PlatformNotSupportedException on windows 7

### ISSUE THREAD

**Issue by soeron** [aspnet/DataProtection#282]
OS: Microsoft Windows [Version 6.1.7601] no SP1 not any Updates as much as I know.

```
Unhandled Exception: System.PlatformNotSupportedException: This operation requires Windows 7 / Windows Server 2008 R2 or later.
   at Microsoft.AspNetCore.Cryptography.CryptoUtil.AssertPlatformIsWindows()
   at Microsoft.AspNetCore.DataProtection.DataProtectionBuilderExtensions.<>c__DisplayClass11_1.<ProtectKeysWithDpapi>b__1(KeyManagementOptions options)
   at Microsoft.Extensions.Options.ConfigureOptions`1.Configure(TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
```
Documentation says that it is supported on Windows7+ 

To reproduce: Create aspnetcore website and add:
```
services.AddDataProtection()
            .ProtectKeysWithDpapi();
```
in ConfigureServices.
Add in project file:
```
<RuntimeIdentifier>win7-x86</RuntimeIdentifier>
```
Publish and run on windows 7 without SP1.
It doesn't matter if dotnet core sdk is installed or not. As looking in the source I guess the OS check can't load 'bcrypt.dll' which is available on the system.

**Comment by soeron** [comment]
Found a solution. Installing [KB2533623](https://www.microsoft.com/en-us/download/details.aspx?id=26767) fixed the issue.

**Comment by blowdart** [comment]
I'll close this then :)
