### ISSUE TITLE
ProtectWithDpapi throws CryptographicException

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/DataProtection#47]
Music Store fails on css when running as `Administrator`

~~~
[ERROR:Microsoft.AspNet.Server.WebListener.MessagePump] ProcessRequestAsync
System.Security.Cryptography.CryptographicException: Access is denied.
   at Microsoft.AspNet.Security.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiImpl(Byte*
 pbSecret, UInt32 cbSecret, Byte* pbOptionalEntropy, UInt32 cbOptionalEntropy, Boolean fLocalMachine)
   at Microsoft.AspNet.Security.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapi(ISecret secret,
Boolean protectToLocalMachine)
   at Mic
rosoft.AspNet.Security.DataProtection.XmlEncryption.DpapiXmlEncryptor.Encrypt(XElement plaintextElement)
   at Microsoft.AspNet.Security.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorConfiguration.Encryp
tSecret(IXmlEncryptor encryptor
)
   at Microsoft.AspNet.Security.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorConfiguration.ToXml(
IXmlEncryptor xmlEncryptor)
   at Microsoft.AspNet.Security.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(Guid keyId, DateT
imeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNet.Security.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate,
DateTimeOffset expirationDate)
   at Microsoft.As
pNet.Security.DataProtection.KeyManagement.KeyRingProvider.CreateCachedKeyRingInstanceUnderLock(DateTime utcNow,
CachedKeyRing existingCachedKeyRing)
   at Microsoft.AspNet.Security.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at M
icrosoft.AspNet.Security.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] unprotectedData)
   at Microsoft.AspNet.SignalR.Infrastructure.DataProtectionProviderProtectedData.Protect(String data, String purpose)
   at Microsoft.AspNet.
SignalR.PersistentConnection.ProcessNegotiationRequest(HttpContext context)
   at Microsoft.AspNet.SignalR.PersistentConnection.<ProcessRequestCore>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Syste
m.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
---
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.WebListener.MessagePump.<ProcessRequestAsync>d__19.MoveNext()
~~~

There is workaround:

~~~C#
services.AddInstance<IXmlEncryptor>(new DpapiXmlEncryptor(true));
~~~

but adding this bug here to investigate. We need to see if this happens under different credentials too.

To repro, try to access the registration page in MusicStore.

**Comment by GrabYourPitchforks** [comment]
@victorhurdugaci does this still repro?

**Comment by victorhurdugaci** [comment]
Yes :disappointed:

**Comment by GrabYourPitchforks** [comment]
Known bug in LSASS in Win10 preview, waiting for fix from Windows team.
