### ISSUE TITLE
Assertion fails typeof(IAuthenticatedEncryptorConfigurationXmlReader).IsAssigna bleFrom(encryptorConfigurationParserType)

### ISSUE THREAD

**Issue by swaggerloaf** [aspnet/DataProtection#53]
Using runtime  1.0.0-beta4-11143 clr     x86
"Microsoft.AspNet.Security.DataProtection": "1.0.0-beta4-10918"

MVC app makes call to Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager
and receives 
System.Security.Cryptography.CryptographicException: Assertion failed: TODO: typeof(IAuthenticatedEncryptorConfigurationXmlReader).Is
bleFrom(encryptorConfigurationParserType)

<pre>
    "dependencies": {
        "EntityFramework.SqlServer": "7.0.0-beta4-*",
        "EntityFramework.Commands": "7.0.0-beta4-*",
        "Microsoft.AspNet.Mvc": "6.0.0-beta4-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta4-*",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta4-*",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4-*",
        "Microsoft.AspNet.Security.Cookies": "1.0.0-beta4-*",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta4-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta4-*",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4-*",
        "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta4-*",
        "Microsoft.Framework.Logging": "1.0.0-beta4-*",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta4-*",
        "Microsoft.AspNet.Security.DataProtection": "1.0.0-beta4-10918"
</pre>
<pre>
Active Version           Runtime Architecture Location                   Alias
------ -------           ------- ------------ --------                   -----
       1.0.0-beta3       clr     x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       clr     x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       coreclr x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       coreclr x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11138 clr     x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11138 coreclr x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11143 clr     x64          C:\Users\Glenn\.k\runtimes
  *    1.0.0-beta4-11143 clr     x86          C:\Users\Glenn\.k\runtimes default
       1.0.0-beta4-11143 coreclr x64          C:\Users\Glenn\.k\runtimes
</pre>
<pre>
[INFORMATION:Microsoft.Net.Http.Server.WebListener] Listening on prefix: http://localhost:5000/
Started
[ERROR:Microsoft.AspNet.Server.WebListener.MessagePump] ProcessRequestAsync
System.Security.Cryptography.CryptographicException: Assertion failed: TODO: typeof(IAuthenticatedEncryptorConfigurationXmlReader).IsAssigna
bleFrom(encryptorConfigurationParserType)
   at Microsoft.AspNet.Cryptography.CryptoUtil.Fail(String message)
   at Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager.ParseKeyElement(XElement keyElement)
   at Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.CreateCachedKeyRingInstanceUnderLock(DateTime utcNow, CachedKeyRing exis
tingCachedKeyRing)
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNet.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] unprotectedData)
   at Microsoft.AspNet.Mvc.AntiForgeryTokenSerializer.Serialize(AntiForgeryToken token)
   at Microsoft.AspNet.Mvc.AntiForgeryTokenStore.SaveCookieToken(HttpContext httpContext, AntiForgeryToken token)
   at Microsoft.AspNet.Mvc.AntiForgeryWorker.SaveCookieTokenAndHeader(HttpContext httpContext, AntiForgeryToken newCookieToken)
   at Microsoft.AspNet.Mvc.AntiForgeryWorker.GetFormInputElement(HttpContext httpContext)
   at Microsoft.AspNet.Mvc.Rendering.DefaultHtmlGenerator.GenerateAntiForgery(ViewContext viewContext)
   at Microsoft.AspNet.Mvc.Rendering.HtmlHelper.AntiForgeryToken()
   at Asp.ASPV__Views_Account_Register_cshtml.<ExecuteAsync>d__13.MoveNext() in /Views/Account/Register.cshtml:line 11
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.ViewExecutor.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.MvcRouteHandler.<InvokeActionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Diagnostics.Entity.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.WebListener.MessagePump.<ProcessRequestAsync>d__19.MoveNext()
</pre>

**Comment by GrabYourPitchforks** [comment]
`Microsoft.AspNet.Security.DataProtection` was renamed to `Microsoft.AspNet.DataProtection`. Update your DataProtection, MVC, Security, and Identity references to latest and the error should go away. Please feel free to reopen this issue if updating does not address the problem.
